### ISSUE TITLE
Failed to build AppImage when updating

### ISSUE THREAD

**Issue by Morphime** [simoniz0r/Discord-Canary-AppImage#1]
On Centos 7
I'm trying to update my discord-canary with the command /path/to/discord-canary.AppImage --update but im getting errors:

Using appimagebuild to build an AppImage for the latest version of Discord Canary...
Downloading aibs for discord-canary...
wget: error while loading shared libraries: libhogweed.so.4: cannot open shared object file: No such file or directory
discord-canary not found!
Failed to build an AppImage for the latest version of Discord Canary.  Please report an issue here: https://github.com/simoniz0r/AppImages/issues

I think the problem is that when i do --update, it downloads the file in my Download Folder and doesnt find my discord-canary there since when i installed it, i installed directly in my /usr/locale/bin folder

**Comment by simoniz0r** [comment]
The update process builds an entirely new AppImage; the location of the old one does not matter.  I'll have to put some more libs into AppImageBuild to avoid this error in the future.

Thanks for the report.  I'll try and have it fixed by the end of the day.

**Comment by simoniz0r** [comment]
On second thought, since I'm already checking to see if the user has wget or curl before downloading `appinagebuild` and attempting to build the new AppImage for Discord, I'll just remove wget from the AppImage of `appimagebuild`.  It should be working now.  I'll have to add `curl` support to `appimagebuild` also to cover more users, but that should be pretty easy to do.

You should now be able to use the `--update` argument on the AppImage that you have without having to redownload it or change anything on your end.  `appimagebuild` is downloaded when you run the `--update` argument, so you'll get the fixed version automatically.

Let me know if you have any issues with this still, thanks!

**Comment by simoniz0r** [comment]
I thought that adding `libhogweed4` would require more dependencies than just `libhogweed4` itself, but seems like that isn't the case.  I've added `libhogweed4` to the AppImage for `appimagebuild`.  If this doesn't work, I'll probably have to go with my other plan here of just removing `wget` from the AppImage and adding `curl` support also.

If you have time, please test the `--update` argument for me and let me know if it's working now that I've bundled `libhogweed4` @Morphime 
Thanks!

**Comment by Morphime** [comment]
I'll test it tomorow when i go back to work and i'll post the result

**Comment by Morphime** [comment]
Here is the result:
Using appimagebuild to build an AppImage for the latest version of Discord Canary...
Downloading aibs for discord-canary...
wget: /lib64/libc.so.6: version `GLIBC_2.22' not found (required by /tmp/.mount_appimaw9q61Y/usr/lib/x86_64-linux-gnu/libgnutls.so.30)
discord-canary not found!
Failed to build an AppImage for the latest version of Discord Canary.  Please report an issue here: https://github.com/simoniz0r/AppImages/issues

**Comment by simoniz0r** [comment]
Alright thanks... that means I'll either have to pack a much older version of `wget` or just not pack it at all.

**Comment by simoniz0r** [comment]
Alrighty, I've updated `appbimagebuild` again with `wget` and its dependencies from Debian Wheezy, so this should definitely work for you.
